version: '3'

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/homechan/sql:/var/lib/postgresql/data"
  app:
    build: .
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/homechan/srv:/srv"
    env_file:
      - .env
    environment:
      DB: postgres
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.homechan-app.rule: "Host(`homechan.${DOMAIN_NAME:-localhost}`)"
  nginx:
    image: nim65s/ndh:nginx
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/homechan/srv/homechan:/srv:ro"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.homechan-ngx.rule: "Host(`homechan.${DOMAIN_NAME:-localhost}`) && PathPrefix(`/static`, `/media`)"
  redis:
    image: redis:alpine

  mqtt:
    build: .
    env_file:
      - .env
    environment:
      DB: postgres
    command: mqttasgi homechan.asgi:application

  matrix:
    build: .
    env_file:
      - .env
    environment:
      DB: postgres
      PYTHONPATH: .
    command: matrix-asgi homechan.asgi:application


networks:
  web:
    external: true
